apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherart-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: etherart-frontend
  template:
    metadata:
      labels:
        app: etherart-frontend
    spec:
      containers:
        - name: frontend
          image: etherart-frontend:latest
          ports:
            - containerPort: 80
